/*
Copyright 2022 Revenu Québec

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify,
merge, publish, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
using System;
using System.Drawing;

namespace VanillaTwist.MEV
{
    /// <summary>
    /// Informations reçues du MEVWEB lors d'une requête de type Transaction
    /// Information received from WEB-SRM during a request of type Transaction
    /// </summary>
    public class ResponseTransaction
    {
        /// <summary>
        /// Numéro du prochain cas d'essais
        /// Next test case number that you must execute.
        /// </summary>
        public String ProchainCasEssai { get; set; }

        /// <summary>
        /// Numéro de la transaction
        /// Transaction number generated by the SRS/POS
        /// </summary>
        public String NoTrans { get; set; }

        /// <summary>
        /// Numéro de transaction du MEV-WEB
        /// Transaction number sent by the WEB-SRM
        /// </summary>
        public String PsiNoTrans { get; set; }

        /// <summary>
        /// Date du MEV-WEB
        /// Date and time (hour, minute and second) the WEB-SRM processed the transaction
        /// </summary>
        public String PsiDatTrans { get; set; }

        /// <summary>
        /// Moment du traitement du lot de transactions( date, heure, minute et seconde).
        /// Date and hour the WEB-SRM the transaction batch was processed
        /// </summary>
        public String datLot { get; set; }

        /// <summary>
        /// Numéro généré par le MEV-WEB qui identifie le lot de transactions
        /// Number generated by the WEB-SRM identifying the batch of transactions
        /// </summary>
        public String noLot { get; set; }

        /// <summary>
        /// Réponse du MEV-WEB suite à la transmission d'une transaction
        /// Information received from WEB-SRM during a request of type Transaction
        /// </summary>
        /// <param name="ProchainCasEssai">Numéro du prochain cas d'essai
        ///                                Next test case number that you must execute.</param>
        /// <param name="NoTrans">Numéro de la transaction
        ///                      Transaction number generated by the SRS/POS</param>
        /// <param name="PsiNoTrans">Numéro de transaction du MEVWEB
        ///                          Transaction number sent by the WEB-SRM</param>
        /// <param name="PsiDatTrans">Date du MEV-WEB
        ///                           Date and hour the WEB-SRM processed the transaction</param>
        /// <param name="datLot">Moment du traitement du lot de transactions( date, heure, minute et seconde).
        ///                      Date and hour the WEB-SRM the transaction batch was processed</param>
        /// <param name="noLot">Numéro généré par le MEV-WEB qui identifie le lot de transactions
        ///                     Number generated by the WEB-SRM identifying the batch of transactions</param>
        public ResponseTransaction( String ProchainCasEssai, String NoTrans, String PsiNoTrans, String PsiDatTrans, String datLot, String noLot )
        {
            this.ProchainCasEssai = ProchainCasEssai;
            this.NoTrans = NoTrans;
            this.PsiNoTrans = PsiNoTrans;
            this.PsiDatTrans = PsiDatTrans;
            this.datLot = datLot;
            this.noLot = noLot;
        }

    }
}
